#!/usr/bin/env sh

set -euo pipefail
set -x

WEBFINGER_STATIC="$ROOT/webfinger.json"

resource=$(printf %s "$QUERY_STRING" | tr '&' '\n' | grep 'resource=' | cut -d'=' -f2 || true)

function error(){
  printf %b "$@\n" >&2
}

function check_resource(){
  test -n "$resource" && jq -r '.subject,.aliases[]' "$WEBFINGER_STATIC" | grep -q -x -F "$resource"
}

function reply_webfinger(){
  printf "Content-Type: application/jrd+json\n\n"
  jq . "$WEBFINGER_STATIC"
}

function reply_not_found(){
  error "no such resource '$resource' at this address"
  printf "Status: 404 Not Found\n\n"
}

if check_resource; then
  reply_webfinger
else
  reply_not_found
fi
exit 0
