---
- name: update server configuration
  hosts: prod
  #become: root
  tasks:
    - name: update webserver configuration file
      ansible.builtin.copy:
        src: root/Caddyfile
        dest: /etc/caddy/Caddyfile
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: update website content files
      ansible.posix.synchronize:
        src: root/public/
        dest: /srv/www/
    - name: updated permissions on website files
      ansible.builtin.file:
        path: /srv/www
        owner: caddy
        group: caddy
        mode: 0744
        recurse: true
    - name: ensure webserver service is up and reloaded
      ansible.builtin.service:
        name: caddy
        state: reloaded
        enabled: true

